### ISSUE TITLE
[ANTI - CRUSH] Unhandled Rejection : Error: Used disallowed intents

### ISSUE THREAD

**Issue by yerlielonmusk** [sandarutharuneth/midjourney-bot#11]
Discord bot is not responding and git bash says that error in the title

**Comment by sandarutharuneth** [comment]
Don't open issues for your own fault for not reading the error properly. Error is self explanatory. Enabled the Intents.

**Comment by yerlielonmusk** [comment]
yeah i closed the issue.That means you don't need to speak

**Comment by Tqnsls** [comment]
Wow, what a nice and friendly owner.
