### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'model')

### ISSUE THREAD

**Issue by algoforextrading** [sandarutharuneth/midjourney-bot#12]
--------------------------------------------------                                              
 █▀█ █▀█ █▀█ ░░█ █▀▀ █▀▀ ▀█▀   █▀█ ▄▀█ ▀█ █▀▀ █▀█
 █▀▀ █▀▄ █▄█ █▄█ ██▄ █▄▄ ░█░   █▀▄ █▀█ █▄ ██▄ █▀▄
--------------------------------------------------
----------------------------------------
[HANDLER - EVENTS] Loaded a file : interactionCreate
[HANDLER - EVENTS] Loaded a file : ready
----------------------------------------
----------------------------------------
[HANDLER -  SLASH] Loaded a file : imagine
[HANDLER -  SLASH] Loaded a file : ping
----------------------------------------
[HANDLER - SLASH] Slash commands has been registered successfully to all the guilds
----------------------------------------
----------------------------------------
[READY] XXX#12323 is up and ready to go.
----------------------------------------
[ANTI - CRUSH] Unhandled Rejection : TypeError: Cannot read properties of undefined (reading 'model')

**Comment by sandarutharuneth** [comment]
Read the ReadMe.md file before open an issue next time. All these explained there

**Comment by algoforextrading** [comment]
I wouldn't be posting If i had not read it, i have sety everything up and when i execute the prompt and i just get this error, the ping works but the image command doenst

**Comment by sandarutharuneth** [comment]
model error only occur on the deprecated code and it was removed and updated to the new one weeks ago. New code doesn't shows the model error and only error it shows is Payment Needed message when the free tries runs out on your API
