### ISSUE TITLE
Cant keep open

### ISSUE THREAD

**Issue by tonodestroy** [sandarutharuneth/midjourney-bot#13]
Good afternoon, I have a problem when executing the program. After a few minutes it closes automatically, leaving no closing error.

Sorry for my bad english. Thanks!

**Comment by sandarutharuneth** [comment]
What is your hosting?

**Comment by tonodestroy** [comment]
is a ubuntu server 22.04

**Comment by tonodestroy** [comment]
the bot works correctly, but it closes automatically

**Comment by sandarutharuneth** [comment]
I don't have much of a experience running discord bots on a Ubuntu server but I'm suggesting to get a host for the bot or run it on vc code terminal. I think your problem is the server. Some servers does turns off automatically if there isn't any activities.

**Comment by tonodestroy** [comment]
Ok, thanks I close the issue
