### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Tresh-King** [sandarutharuneth/midjourney-bot#6]
![image](https://user-images.githubusercontent.com/132993532/237041983-b9c0e190-9734-4844-bbf0-9964960cd6a0.png)
![image](https://user-images.githubusercontent.com/132993532/237043365-650758a3-2229-47bf-84ef-f845431d618e.png)
![image](https://user-images.githubusercontent.com/132993532/237043406-77a5b8bb-2551-4f02-b6bf-1a9124a2e60e.png)
![image](https://user-images.githubusercontent.com/132993532/237043532-3db7b99e-3c2d-48c0-ac1f-5928e13e369d.png)

When I call discord, I use /imagine prompt: neon light sign in design of face | of gorgeous goddess | detailed gorgeous face | precise lineart | intricate | realistic | studio quality | cinematic | luminescence | character design | concept art | highly detailed | illustration | digital art | digital painting, the error is as follows, how to solve it? replicate has no call record, and the apikey is available

**Comment by sandarutharuneth** [comment]
Are you sure that you filled the right information on the `config.json` file and didn't change anything else on the code?

**Comment by sandarutharuneth** [comment]
Code is works perfectly fine for me. Try `npm i` on console again. Follow the instructions on the readme file. Also if you don't have free credits left on Replicate, you can't generate images till next month unless you pay for the API.

**Comment by sandarutharuneth** [comment]
> Is the token userToken or botToken? Also, is the owner parameter the user id in the discord settings? Can you explain me how to get these parameters? It may be that the parameters of this piece are wrong. I am sure that the replicate key is available and the code has not been changed, and the dependencies are normal

First This is a discord bot and obviously token must be the BOT TOKEN ( Common Sense ) and there is nothing changes on the dependencies from the previous release. Only some bugs fixed on the code. And yes Owner ID means your User ID. Please read the release notes and adapt to the changes.

**Comment by adminlove520** [comment]
> > Is the token userToken or botToken? Also, is the owner parameter the user id in the discord settings? Can you explain me how to get these parameters? It may be that the parameters of this piece are wrong. I am sure that the replicate key is available and the code has not been changed, and the dependencies are normal
> 
> First This is a discord bot and obviously token must be the BOT TOKEN ( Common Sense ) and there is nothing changes on the dependencies from the previous release. Only some bugs fixed on the code. And yes Owner ID means your User ID. Please read the release notes and adapt to the changes.

So what permissions should I configure for the bot? Just now I changed to botToken and UserId, but still reported the same error

**Comment by sandarutharuneth** [comment]
> > > Is the token userToken or botToken? Also, is the owner parameter the user id in the discord settings? Can you explain me how to get these parameters? It may be that the parameters of this piece are wrong. I am sure that the replicate key is available and the code has not been changed, and the dependencies are normal
> > 
> > 
> > First This is a discord bot and obviously token must be the BOT TOKEN ( Common Sense ) and there is nothing changes on the dependencies from the previous release. Only some bugs fixed on the code. And yes Owner ID means your User ID. Please read the release notes and adapt to the changes.
> 
> So what permissions should I configure for the bot? Just now I changed to botToken and UserId, but still reported the same error

Join support server and open a ticket

**Comment by sandarutharuneth** [comment]
> Could you please write a deployment document?

There is already all the startup guide on the readme file. Please read and follow. So far you're the only 2 people seem to have issues with the code. Code is works all of us perfectly fine.

ReadMe File: https://github.com/sandarutharuneth/midjourney-bot#readme
